default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d9hcojuq1p3s739mdl4g-a.oregon-postgres.render.com
  port: 5432
  username: kaihatubteam_db_user
  password: Nnkpr0c8KWgdWp0eTJnZR7PElEdi7rgz

development:
  <<: *default
  database: kaihatubteam_db

test:
  <<: *default
  database: kaihatubteam_test

production:
  <<: *default
  database: kaihatubteam_production
